### ISSUE TITLE
k8s version vs lib version

### ISSUE THREAD

**Issue by petr-k** [ksonnet/ksonnet-lib#109]
Hi,
just a question here: could you please clarify what is the relationship between Kubernetes version and ksonnet-lib version? E.g., can I safely use `ksonnet.beta.3` (which is generated from API 1.8.0) against Kubernetes 1.7.0? Are there things to watch out for?

Thanks.

**Comment by bryanl** [comment]
In general, you won't be able to use items that weren't specified in Kubernetes 1.7.0. The pre-generated libraries are going away, and we'll provide a generator, so the ksonnet-lib you are using will match your environment.
