### ISSUE TITLE
Can't reference ingressRule in ksonnet-lib

### ISSUE THREAD

**Issue by biwwy** [ksonnet/ksonnet-lib#117]
When trying to create an ingress rule and referencing ingressRule in API with something like `local rule = $.extensions.v1beta1.ingressRule,` I get an error stating that field doesn't exist. What am I doing wrong?

**Comment by bryanl** [comment]
There's two ways you can approach this:

```
local rule = k.extensions.v1beta1.ingress.mixins.spec.rulesType.new()
```

or

```
local rule = hidden.extensions.v1beta1.ingressRule.new()
```

Let me know if you need any more pointers?

**Comment by biwwy** [comment]
Just to clarify I can easily reference say deployment with `local deployment = $.apps.v1beta1.deployment,` $ being the core k.libsonnet and therefore k8s.libsonnet library.

**Comment by bryanl** [comment]
Yes, but `ingressRule` is in a different location. Notice that it starts with `hidden`.

**Comment by biwwy** [comment]
Oh, thanks! Figured it. `hidden` API parts can be referenced through links in core API, such as with rulesType here.

Thanks!

**Comment by biwwy** [comment]
Closing
