### ISSUE TITLE
Resolve tags to digests as part of translation

### ISSUE THREAD

**Issue by mattmoor** [ksonnet/ksonnet-lib#18]
Pretty please.

**Comment by jbeda** [comment]
I'm missing context here.  Can you give some examples?

**Comment by mattmoor** [comment]
If I understand the origins of this correctly, the (internal) tool this is meant to emulate resolved mutable package "labels" to immutable package identifier (uuids).  I hope you catch my drift :)

Today Kubernetes relies on the myth of immutable tags, and therefore lacks strong image consistency across auto-scaling an auto-healing.  Even "Pull Always" (while better) is wrong for this, what's almost always the right answer is performing mutable label resolution to an immutable reference at a cut point to ensure image consistency.  This is such a cut point.

See: https://github.com/kubernetes/kubernetes/issues/1697

**Comment by mattmoor** [comment]
Simply:
```
gcr.io/google-containers/pause:2.0
=>
gcr.io/google-containers/pause@sha256:9ce5316f9752b8347484ab0f6778573af15524124d52b93230b9a0dcc987e73e
```

**Comment by jbeda** [comment]
Hmm -- we probably want a new intrinsic that is only available for ksonnet that would be something like `resolveContainerImage(string)` that will take a container image and make sure it is fully resolved.  This is obviously something that will have side effects and will prevent the ksonnet evaluation from being 100% hermetic.

To get around that, I'd suggest that we provide a way to have folks control that resolution with some flags/config to kubecfg (or whatever implements this jsonnet extension):
* Do a live resolve.  This means that it will hit the network and every evaluation may be different.
* Don't do any resolution.  Leave things late bound.  This will mean that resolution will be done at deploy time.
* Have an explicit resolution map.  This would translate names to sha's
  * Error if an image isn't in the resolution map
  * Hit the network if an image isn't in the resolution map.

To get here we'd need to (a) have a preferred way to evaluate jsonnet beyond the jsonnet binary and (b) have that implementation implement the extension.  This would probably happen after we finish the go port of jsonnet.

**Comment by hausdorff** [comment]
Jsonnet exposes an "escape hatch" from its strict hermiticity: the flag, `--ext-str <var>[=<val>]` allows you to pass a variable from the command line and then access it in the source the source using the standard function [`std.extVar`](http://jsonnet.org/docs/stdlib.html#ext_vars).

I'm wondering if it makes sense for `ksonnet-lib` to leave a call to `std.extVar` in the image for a client to fill in (either `kubectl` or [`kubecfg`](https://github.com/ksonnet/kubecfg)), which would involve the client (1) calling out to DockerHub (or whatever registry) to resolve the tag, and (2) passing the SHA as an `--ext-str` into Jsonnet, which is then filled in when the Jsonnet is expanded to JSON.

The impetus behind this is mostly that I think there will be a call for a lot of demand for stuff like this, and I tend to like having a strong distinction between `ksonnet-lib` and the compiler driver (_e.g._, `kubecfg`), which handles state and stuff, and invokes the Jsonnet compiler with whatever stuff it needs to expand out to JSON.

Also, cc @anguslees, who is (1) also ex-google, and (2) author of `kubecfg`

**Comment by jbeda** [comment]
I can see 5 places to do image label -> sha resolution:
1. Explicit map or parameter outside of the toolchain.  Ensure/warn that images use sha.  Admission controller server side?
2. During jsonnet evaluation time
3. Some other client side filter/plugin
4. Admission time with a new modifying admission controller
5. At run time -- depending on pull policy.

Right now we are at (5).  I kind of like (1) and (5)

**Comment by anguslees** [comment]
As discussed on slack a few days ago (I was unaware there was a corresponding github issue until now), I think the various admission controller approaches are going to be too hard:  there are many places where an image reference can be "hidden", like in json-serialised annotations.

So _I_ think this reduces the viable options to only (2) and (5) - ie: the client-side and server-side points that have intimate knowledge of exactly where image references occur in the soup of API json.

(5) is what we currently have and it obviously works well, but suffers from the issues the OP is raising: even though we like to imagine that not-latest tags are immutable/write-once, they're not, and may be inconsistent between pods in a replicaset, etc.

So I think the only improvement left to us is (2): offer a mechanism to "mark" all references to images, and use it to "freeze" image tags to immutable ids (sha256 digests) during jsonnet evaluation.

The implementation is actually quite straightforward, and something I was already planning to add to `kubecfg`.  It _does_ mean we suddenly start to require `kubecfg` or something similarly k8s-specific and no longer support the vanilla `jsonnet` tool. _I_ see this as inevitable, but I'm not sure how the other ksonnet members feel about that...

Corresponding kubecfg feature-request bug: https://github.com/ksonnet/kubecfg/issues/13

**Comment by anguslees** [comment]
Fwiw, this was implemented in https://github.com/ksonnet/kubecfg/pull/30 - I don't know what we want to do with this ksonnet-lib issue.

To use the kubecfg feature, we need to wrap image names in `std.native("resolveImage")(img)` (or import `kubecfg.libsonnet` and use `kubecfg.resolveImage(img)`).  This will do nothing by default, but will look up (public) docker registries and convert to name@digest form with `kubecfg --resolve-images=registry`.

**Comment by hausdorff** [comment]
I haven't had time to really look at this yet, but it certainly looks promising. For me the lingering question is when expansion actually should happen. (_e.g._, I'm not sure whether it could be argued that it should happen before ksonnet expansion)

**Comment by bryanl** [comment]
This is no longer a feature of ksonnet-lib. ksonnet in 0.12+ can resolve images when setting parameters.
