### ISSUE TITLE
Found invalid field hostMappings for v1.PodSpec

### ISSUE THREAD

**Issue by falfaro** [ksonnet/ksonnet-lib#20]
I've been trying to use ksonnet-lib with Kubernetes 1.6.2 but there's no way I can get Kubernetes to accept the JSON code generated from the example file hello-nginx.jsonnet:

```
$ jsonnet --version
Jsonnet commandline interpreter v0.9.3
$ git clone https://github.com/ksonnet/ksonnet-lib
$ cd ksonnet-lib/examples/
$ jsonnet hello-nginx.jsonnet > hello-nginx.json
$ kubectl create -f hello-nginx.json
error: error validating "hello-nginx.json": error validating data: found invalid field hostMappings for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by hausdorff** [comment]
Yes, sorry, the library still has quite a few rough edges. I'll look into fixing it tonight.

**Comment by falfaro** [comment]
Well, more than a few rough edges. I haven't been able to get it do anything so far ;-)

**Comment by hausdorff** [comment]
Yes, sorry. :) We're working on it as we speak. In the meantime if it is helpful maybe I get something custom together so you can make progress?

**Comment by falfaro** [comment]
Yes, I'm willing to test any quick hack :-)

**Comment by hausdorff** [comment]
As an update, this will be resolved when (1) [this PR to the Jsonnet language](https://github.com/google/jsonnet/pull/318) lands, and (2) when PR #24 lands, which should be ~soon. At that point we'll update the examples and add some beefier end-to-end examples.

**Comment by hausdorff** [comment]
Ok, both of these things have happened. New examples will land next week. So I will expect to close this at that point.

**Comment by hausdorff** [comment]
Ok, prod-ready examples are now available in [ksonnet/mixins](https://github.com/ksonnet/mixins). I'll close this now, but @falfaro what are your thoughts? We can re-open it if you are not satisfied.
