### ISSUE TITLE
ksonnet-gen seems not work properly or I am missing something

### ISSUE THREAD

**Issue by ngtuna** [ksonnet/ksonnet-lib#25]
So, I tried ksonnet-gen with k8s 1.6.0 and 1.7.0-beta.0 tags and they both didn't work. Here below is what I did:

```console
// with k8s v1.6.0 tag
$ ksonnet-gen ~/workspace/gocode/kubernetes/src/k8s.io/kubernetes/api/openapi-spec/swagger.json .
Unrecognized Kubernetes version 'v1.6.0'

// with k8s v1.7.0-beta.0
$ ksonnet-gen ~/workspace/gocode/kubernetes/src/k8s.io/kubernetes/api/openapi-spec/swagger.json .
Failed to emit ref mixin:
Can't make API object from name with nil version in path: 'io.k8s.apimachinery.pkg.runtime.RawExtension'
```

cc/ @hausdorff

**Comment by hausdorff** [comment]
I'll take a look when i get into office (on bus now) but take a look at the open pr which has the sha of the k8s head we're building against.

**Comment by moderation** [comment]
This commit? https://github.com/ksonnet/ksonnet-lib/commit/3c50b831cda82c3a01154167c2685044720f0d9a

**Comment by ngtuna** [comment]
@hausdorff I looked into the PR #24 but saw no sha. Could you ?

**Comment by hausdorff** [comment]
https://github.com/hausdorff/ksonnet-lib/commit/deb5ab902f7bf8290cc5df1dfdece38465e84f66#diff-1f7b62afc49bfd99c29058f73dfc5486 This file should have it at the top. I can't see it though because I'm on mobile.

**Comment by ngtuna** [comment]
Okay thanks I got it now. So should we support old k8s releases like 1.5.x or 1.6.x ?

**Comment by hausdorff** [comment]
Yeah we should, I just haven't generated rewrite rules for those versions yet. Soon!

**Comment by hausdorff** [comment]
One more thing, now that I'm back at my desk: this codegen generates `ksonnet.beta.2`, which you can probably tell from the PR is not yet checked in. `ksonnet.beta.2` depends on [this PR](https://github.com/google/jsonnet/pull/318) to the Jsonnet, which in part resolves #20. If you'd like to use beta.2, you should build the version of Jsonnet in that PR.

**Comment by ngtuna** [comment]
Thanks @hausdorff 👍 

So I wonder how can I generate `ksonnet.beta.1` with all `apps`, `core`, `extensions` separately as showed in the repo ? Using ksonnet-gen I now have `k8s.libsonnet` only.

And could you give me access to the ksonnet slack? My email is tuna@bitnami.com

**Comment by hausdorff** [comment]
The code that generated that is in this commit: https://github.com/ksonnet/ksonnet-lib/commit/c09e19ed377592099cb4b635601147d166bd07ef

But, to be completely frank I would say you are almost certainly better off just starting from `ksonnet.beta.2`, particularly since the different API groups like `core`, `apps`, _etc_., as well as all their versions (`core.v1`, `apps.v1beta1`, _etc_.) are all in `k8s.libsonnet`.

**Comment by ngtuna** [comment]
Yeah I know. But to be honest I am pretty new to jsonnet in general and ksonnet in particular. So I am curious how to start from ksonnet-gen to the final library files as you said `ksonnet.beta.2` :-) And thanks for the slack invitation 👍

**Comment by hausdorff** [comment]
Alright, let us know if you have more questions.

**Comment by ngtuna** [comment]
Okay thanks @hausdorff
I'm happy to close this issue now
