### ISSUE TITLE
Dunno how to declare labels

### ISSUE THREAD

**Issue by ngtuna** [ksonnet/ksonnet-lib#27]
People would like to add some labels (probably it's required) to deployment and/or service. Need to have a clear way to do that with ksonnet. Here below I have this error:

```console
$ cat nginx-deployment.jsonnet
local k = import "../../ksonnet.beta.1/k.libsonnet";
local container = k.core.v1.container;
local deployment = k.apps.v1beta1.deployment;
local prune = k.util.prune;
local label = {app: "nginx"};

// Create nginx container with container port 80 open.
local nginxContainer =
  container.default("nginx", "nginx:1.13.0") +
  container.helpers.namedPort("http", 80);

// Create default `Deployment` object from nginx container.
prune(deployment.default(
  "nginx-deployment", nginxContainer) +
  deployment.mixin.spec.replicas(5) +
  deployment.mixin.spec.labels(label)
  )

$ jsonnet  nginx-deployment.jsonnet
RUNTIME ERROR: Field does not exist: labels
	nginx-svc.jsonnet:16:3-30	thunk <thing>
	../../ksonnet.beta.1/util.libsonnet:4:17-21	
	../../ksonnet.beta.1/util.libsonnet:4:8-22	thunk <a>
	../../ksonnet.beta.1/util.libsonnet:4:8-33	function <anonymous>
	../../ksonnet.beta.1/util.libsonnet:4:8-33	function <prune>
	nginx-svc.jsonnet:(13:1)-(17:3)	
```

**Comment by hausdorff** [comment]
You're right, `ksonnet.beta.1` probably should have this field built into the `deployment.default`. But rather than populating a bunch of default `{}` values for fields, I think it would be better to wait for Jsonnet's PR #318 to land, which will solve this problem for all such situations. Does that work for you?

**Comment by hausdorff** [comment]
So, practically speaking, if you never want to be bothered again by this family of issues, you can build the Jsonnet version in that PR (it's a pretty streamlined build process), and then use that to compile your Jsonnet code.

That should hold you over until it lands and makes it into package managers.

**Comment by ngtuna** [comment]
Ack. Thanks @hausdorff

**Comment by ngtuna** [comment]
I am gonna close this as the PR 318 solved the problem
