### ISSUE TITLE
ksonnet-lib not handling intorstring correctly

### ISSUE THREAD

**Issue by chuckha** [ksonnet/ksonnet-lib#31]
Using the beta2 generated api I was expecting something like this to work:

```.jsonnet
local esProxyStrategy = 
    strategy.new() +
    strategy.rollingUpdate.maxSurge(2);
```
But it did not and @hausdorff told me that it was because the ksonnet-lib was not handling Kubernetes' intorstring type correctly.

**Comment by hausdorff** [comment]
Yeah, that's a problem with `ksonnet-lib` code gen, I'll get a fix together today.

**Comment by chuckha** [comment]
Same with this code:

```
local esProxyServicePort =
    servicePort.new() +
    servicePort.port(9222) +
    servicePort.protocol("TCP") +
    servicePort.mixin.targetPort(8080);
```
I end up with this error:
```
RUNTIME ERROR: Only functions can be called, got object
```
