### ISSUE TITLE
Autogen casing is a bit weird

### ISSUE THREAD

**Issue by chuckha** [ksonnet/ksonnet-lib#33]
I'm seeing things like `aPIVersion` which I expect is some "downcase first letter" rule that wasn't expecting an acronym.

I don't know if this actually matters though. Feel free to close.

**Comment by hausdorff** [comment]
Which version are you using? In `beta.2` this should be fixed with our rewrite rules ([_i.e._](https://github.com/ksonnet/ksonnet-lib/blob/master/ksonnet-gen/kubeversion/data.go#L11))

**Comment by chuckha** [comment]
yeah, i am using `beta.2`

**Comment by hausdorff** [comment]
Oh, I should have just searched for that string. You're right, we seem to have missed this, somehow.
