### ISSUE TITLE
A good example of using beta.2

### ISSUE THREAD

**Issue by ngtuna** [ksonnet/ksonnet-lib#35]
I am looking for a good example to start writing my manifests using beta.2 at master branch. `example/readme/hello-nginx.jsonnet` is still beta.1 and some demo* files at `sigapp` branch don't work for master branch.

**Comment by hausdorff** [comment]
Working on it. Hoping to have time to do this next week.

**Comment by hausdorff** [comment]
@ngtuna I believe we can now close this issue, since we have an example of a production-ready use of beta.2 in the [ksonnet/mixins](https://github.com/ksonnet/mixins) repository.

What do you think?

**Comment by ngtuna** [comment]
Great. Thanks @hausdorff for the info. Yes, I am closing this
