### ISSUE TITLE
Remove no-op constructors.

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet-lib#38]
Stuff like `containerPort.new()` is a no-op. Consider just omitting this.

**Comment by chuckha** [comment]
this is not the case with `k.extensions.v1beta1.deployment.new()` because that yields:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
```

Is there some difference between the two?

**Comment by hausdorff** [comment]
Yes, we want to remove only the no-op constructors. Top-level API objects set `kind` and `apiVersion`.

**Comment by hausdorff** [comment]
Actually, we need these right now, because we need the zero value on the lhs for the mixins to work. For example `{} + {f+: 3}` works, but `{f+: 3}` does not.
