### ISSUE TITLE
Extend kubectl allowing usage of jsonnet file in input

### ISSUE THREAD

**Issue by fabriziopandini** [ksonnet/ksonnet-lib#42]
This will simplify usage of ksonnet embedding 
```bash
jsonnet -J /path/to/ksonnet-lib <filename.libsonnet>
```
Into `kubectl`.

The user will simply do:
```bash
kubectl <command> -<options> <filename.jsonet/libsonnet or ksonnet>
```

**Comment by hausdorff** [comment]
Just so I understand, are you proposing to add a `kubectl` extension? We're definitely considering it, but it probably won't be for a month or two that we will even start thinking about it.

**Comment by hausdorff** [comment]
Alternatively, have a look at [kubecfg](https://github.com/ksonnet/kubecfg) which makes a lot of these sorts of things more simple.

**Comment by fabriziopandini** [comment]
@hausdorff I'm not thinking to any possible solution so far.... I just thought that having the power of ksonnet accessible in a transparent way from kubecfg would be simple and straightforward, so I shared the idea 😎
However I will have a look at kubecfg; is there also some doc/tutorial online or only the github repo?

**Comment by hausdorff** [comment]
@fabriziopandini I think just the README so far. We will hopefully have more to share soon.

**Comment by hausdorff** [comment]
Let's close this for now, since it's not clear that there are action items for us to do. If you have a different view, feel free to suggest another course of action.
