### ISSUE TITLE
group in `apiVersion` is not emitted correctly in all cases

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet-lib#44]
`apiVersion` usually takes the form `group/version`. In the future, `group` will be a domain, rather than a single word (as old groups are).

We currently don't handle this correctly. We need to get the real group out of the fields that look like this:

```
    "x-kubernetes-group-version-kind": [
     {
      "Group": "rbac.authorization.k8s.io",
      "Version": "v1alpha1",
      "Kind": "ClusterRole"
     }
    ]
```

**Comment by tomwilkie** [comment]
I'm getting `Error: the server could not find the requested resource` when using kubecfg to manage some ClusterRoles, unless I change this:

```diff
$ git diff
diff --git a/ksonnet.beta.2/k8s.libsonnet b/ksonnet.beta.2/k8s.libsonnet
index ded3685..748c59a 100644
--- a/ksonnet.beta.2/k8s.libsonnet
+++ b/ksonnet.beta.2/k8s.libsonnet
@@ -7074,7 +7074,7 @@
       },
     },
     v1beta1:: {
-      local apiVersion = {apiVersion: "rbac/v1beta1"},
+      local apiVersion = {apiVersion: "rbac.authorization.k8s.io/v1beta1"},
       // ClusterRole is a cluster level, logical grouping of PolicyRules that can be referenced as a unit by a RoleBinding or ClusterRoleBinding.
       clusterRole:: {
         local kind = {kind: "ClusterRole"},
```

Is this the same issue?

**Comment by hausdorff** [comment]
Sorry, we've been busy. Yes, this is the same issue. I will try to have a fix together in the next couple days.

**Comment by hausdorff** [comment]
@tomwilkie Just kidding, I decided to fix it now. Please have a look at the last two commits of PR #46, and let me know if you see any issues.

**Comment by tomwilkie** [comment]
They look good to me!
