### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by yanana** [ksonnet/ksonnet-lib#49]
I'd like to use ksonnet on deployment, while I don't want to install neither jsonnet nor ksonnet. Instead I want to use the official Docker image containing ksonnet (and jsonnet) as a command. Of course it's easy to create such an image by myself. But the official image is preferable to my own ones, I think.

**Comment by hausdorff** [comment]
This is a good idea. I'll try to pull this together some time in the next few days.

**Comment by hausdorff** [comment]
This is resolved now: https://github.com/ksonnet/ksonnet-lib/blob/master/Dockerfile

You can write a function like below and call `ksonnet <args, files, etc>` and it will work like it's installed on your filesystem.

```bash
ksonnet() {
  docker run -it --rm   \
    --volume "$PWD":/wd \
    --workdir /wd       \
    ksonnet             \
    jsonnet "$@"
}
```

**Comment by anguslees** [comment]
Not the original request, but consider also just downloading a [kubecfg release](https://github.com/ksonnet/kubecfg/releases).  It's a single pre-built binary that statically includes jsonnet, so it's very easy to install (for common architectures).

**Comment by yanana** [comment]
@anguslees Could kubecfg be complete alternative to ksonnet?

**Comment by yanana** [comment]
@hausdorff Does the image exist in any public Docker repository?

**Comment by hausdorff** [comment]
@yanana `kubecfg` is part of the ksonnet project. And, the image does not exist anywhere official, I'm not sure where we should put it. But it should be trivial enough to build.

**Comment by yanana** [comment]
@hausdorff Thanks for your reply. I'm going to see `kubecfg` deeper. And I believe the most important thing is that the official image, in particular version, is available publicly. I and my colleagues hope they were published on Docker Hub. In other words, we want to pull the image as `docker pull ksonnet/ksonnet-lib`.

**Comment by hausdorff** [comment]
@yanana Alright, I'll put the image in `ksonnet/ksonnet-lib`, and we'll maintain that. I believe @anguslees has access to the ksonnet Dockerhub, though, so we have to wait until he gets back online. (He lives in Australia.)

**Comment by hausdorff** [comment]
Alright, @yanana you can obtain obtain the official image from[1]. You will probably want to use the `ksonnet/ksonnet-lib:beta.2`.

https://hub.docker.com/r/ksonnet/ksonnet-lib/tags/

**Comment by yanana** [comment]
@hausdorff I appreciate your dedication.  It looks working well 👍

**Comment by redbaron** [comment]
Images on docker hub are not being updated :(
