### ISSUE TITLE
A list of constructors that could be better

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet-lib#51]
* authorization.v1.LocalSubjectAccessReview
* authorization.v1.SelfSubjectAccessReview
* authorization.v1.SubjectAccessReview
* autoscaling.v1.HorizontalPodAutoscaler
* autoscaling.v2alpha1.horizontalPodAutoscaler
* batch.v1.Job
* batch.v2alpha1.CronJob
* certificates.v1beta1.CertificateSigningRequest
* core.v1.Endpoints
* core.v1.Event
* core.v1.LimitRange
* core.v1.Node
* core.v1.PersistentVolume
* core.v1.PersistentVolumeClaim
* core.v1.Pod
* core.v1.PodTemplate
* core.v1.ReplicationController
* core.v1.ResourceQuota
* core.v1.Secret
* policy.*
* rbac.*
* settings.*
* storage.*

Things in [cluster](https://kubernetes.io/docs/api-reference/v1.7/#-strong-cluster-strong-)

**Comment by chuckha** [comment]
Humbly requesting `core.v1.namespace` constructor that takes a name.

**Comment by hausdorff** [comment]
@chuckha should be resolved in #63

**Comment by adamdecaf** [comment]
Is this a subset of https://github.com/ksonnet/ksonnet-lib/issues/91?
