### ISSUE TITLE
[docs] Incompatible links between README and tutorial on the official website

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet-lib#60]
The links between the main README and the tutorial doc are broken. I'm not 100% sure how to fix this, given that we don't want to break either the Github repo linking or the website linking. (Currently the Github linking works but the website doesn't).

Specifically: the tutorial link in http://ksonnet.heptio.com/docs/core-packages/ksonnet-lib.html#mixins and the readme link in http://ksonnet.heptio.com/docs/tutorial.html don't work.

**Comment by GuessWhoSamFoo** [comment]
Closed as `/docs/core-packages/` no longer exists and readme is no longer linked in the tutorial
