### ISSUE TITLE
io.k8s.kubernetes.pkg.api.v1.LocalVolumeSource confuses Jsonnet

### ISSUE THREAD

**Issue by amir** [ksonnet/ksonnet-lib#69]
Hi,

I'm using `ksonnet-gen` in https://github.com/amir/iron_jsonnet to generate `k8s.libsonnet`. The library gets generated successfully but Kubernetes resource `io.k8s.kubernetes.pkg.api.v1.LocalVolumeSource` gets translated to `local::` which confuses Jsonnet. Looking at the `k8s.libsonnet` in `ksonnet.beta.2` I don't see that resource but I can't find how it's been renamed/removed. Is there a manual step involved after generating the library?

I'm using sed in my project to replace it but before contributing a fix I wanted to make sure it's something you've encountered before too.

**Comment by bryanl** [comment]
This no longer happens with ksonnet-lib 0.1.0.
