### ISSUE TITLE
References to missing hidden.core.v1.persistentVolumeClaim

### ISSUE THREAD

**Issue by glindste** [ksonnet/ksonnet-lib#77]
There are several references in k8s.libsonnet to the field `hidden.core.v1.persistentVolumeClaim` which does not exist. However there is a field in `core.v1.persistentVolumeClaim` which seems to fit the bill. I assume it was moved but the references weren't updated for some reason.

**Comment by bryanl** [comment]
`hidden.core.v1.persistentVolumeClaim` exists in ksonnet-lib 0.1.0

**Comment by sillydong** [comment]
still there are errors came out saying persistentVolumeClaim not found
```
bash-5.0# jsonnet -J /root/deploy/roles/app-platform/../../  -m /etc/jimu/manifests/platform/minio  --ext-str-file config=/etc/jimu/hostvars  /root/deploy/roles/app-platform/files/app/minio.jsonnet
RUNTIME ERROR: field does not exist: persistentVolumeClaim
        /root/deploy/roles/app-platform/../../jsonnet/ksonnet-lib/v1.10.0/k8s.libsonnet:1939:40-76      object <anonymous>
        /root/deploy/roles/app-platform/files/app/minio.jsonnet:136:13-60       object <anonymous>
        During manifestation
```
the code calling it was
```
local k = import 'jsonnet/ksonnet-lib/v1.10.0/k.libsonnet';
local statefulset = k.apps.v1.statefulSet;

{
    'test': statefulset.mixin.spec.volumeClaimTemplatesType            
}
```

I have checked the k8s.libsonnet, there is persistentVolumeClaim exists in `hidden.core.v1.persistentVolumeClaim`

Am I wrong using this?
