### ISSUE TITLE
VS Code Jsonnet Preview failed

### ISSUE THREAD

**Issue by gangliao** [ksonnet/ksonnet-lib#95]
```
local params = std.extVar("__ksonnet/params").components["teamcity-server-instance"];
local k = import "k.libsonnet";
local deployment = k.apps.v1beta1.deployment;
local container = k.apps.v1beta1.deployment.mixin.spec.template.spec.containersType;
local containerPort = container.portsType;
local service = k.core.v1.service;
local servicePort = k.core.v1.service.mixin.spec.portsType;

local targetPort = params.containerPort;
local nodePort = params.nodePort;
local labels = {app: params.name};
```

VS Code Jsonnet Preview:

```
RUNTIME ERROR: Undefined external variable: __ksonnet/params
	/Users/liaogang/Desktop/Anonym/CI/teamcity/components/teamcity-server-instance.jsonnet:1:16-45	thunk 
	/Users/liaogang/Desktop/Anonym/CI/teamcity/components/teamcity-server-instance.jsonnet:15:5-10	thunk 
	/Users/liaogang/ksonnet-lib/ksonnet.beta.3/k8s.libsonnet:8747:87-90	thunk 
	/Users/liaogang/ksonnet-lib/ksonnet.beta.3/k8s.libsonnet:8820:60-63	object 
	/Users/liaogang/ksonnet-lib/ksonnet.beta.3/k8s.libsonnet:8751:47-67	object 
	/Users/liaogang/Desktop/Anonym/CI/teamcity/components/teamcity-server-instance.jsonnet:31:21-30	thunk 
	/Users/liaogang/ksonnet-lib/ksonnet.beta.3/k.libsonnet:60:59-73	object 
	During manifestation	
```

**Comment by charlesa101** [comment]
still failing for me as well

**Comment by bryanl** [comment]
There is a fix for it, and we are working with Microsoft to fix publishing for the jsonnet plugin. Will update here when it is resolved.

**Comment by bryanl** [comment]
This has been updated and the functionality is present is the jsonnet 0.1.0 extension.

**Comment by yanc0** [comment]
I still have the error, even if jsonnet plugin is up to date (0.1.0).

![screenshot from 2018-05-23 08-09-49](https://user-images.githubusercontent.com/3806094/40406394-cbecd0e6-5e60-11e8-928b-1650bffe3a65.png)

**Comment by charandas** [comment]
@yanc0 I noticed that `Cmd+Shift+I` under `environments` folder does error out like you say. However, it works when any individual component file is open. 

I also get squiggles on `std.extVar("__ksonnet/params")` calls under `*.(jsonnet|libsonnet)` files under the environment folder. However, under components folder, the plugin is ok with those `extVar`s.

@bryanl thoughts?
